version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
  app:
    build: .
    restart: always
    ports:
      - 5000:80
    environment:
      MongoDB__NAME: UserDB
      MongoDB__Host: mongo
      MongoDB__PORT: 27017
      MongoDB__USER: root
      MongoDB__PASSWORD: example
    depends_on:
      - mongo
